import { motion } from "framer-motion";
import { 
  Users, FileCheck, AlertTriangle, 
  Plug, Shield, CheckCircle 
} from "lucide-react";

const CoreFeatures = () => {
  const features = [
    {
      icon: Plug, // Using Plug as placeholder/generic if specific icon not found, or matching original logic
      title: "Living Knowledge Graph",
      goal: "Anseru connects directly to your real sources of truth: content, past RFPs, security documents, and public content.",
      capabilities: [
        "Each source is indexed with ownership, freshness, and expiry",
        "Improves accuracy with usage instead of decaying over time"
      ]
    },
    {
      icon: Users,
      title: "Cross-Team Collaboration & Workflow",
      goal: "Collaborate seamlessly across sales, pre-sales, product, legal, and security teams.",
      capabilities: [
        "Real-time editing and commenting",
        "Role-based access and approvals",
        "Task tracking to assign ownership and reduce bottlenecks"
      ]
    },
    {
      icon: FileCheck,
      title: "Evidence & Citation Engine",
      goal: "Every answer generated by Anseru is backed by real evidence.",
      capabilities: [
        "Automatic source citations",
        "Secure document links instead of attachments",
        "Full traceability from answer to underlying document"
      ]
    },
    {
      icon: AlertTriangle,
      title: "Knowledge Health & Risk Monitoring",
      goal: "Expose risk before submission, not after.",
      capabilities: [
        "Monitors expiring certifications, outdated policies, and missing ownership",
        "Shifts the problem from 'Did AI hallucinate?' to 'Which document needs updating?'"
      ]
    },
    {
      icon: Plug,
      title: "Enterprise Integrations",
      goal: "Integrate effortlessly with your existing revenue and security stack.",
      capabilities: [
        "Connects with CRM systems, cloud storage providers, and communication tools",
        "Fits into existing workflows instead of forcing teams to change"
      ]
    },
    {
      icon: Shield,
      title: "Governance, Analytics & Audit Readiness",
      goal: "Stay in control at every stage of the response lifecycle.",
      capabilities: [
        "Detailed activity logs with user actions and approval tracking",
        "Analytics on response quality, coverage gaps, and cycle times",
        "Audit-ready operations by default"
      ]
    }
  ];

  return (
    <section className="py-0 bg-[#FAFAFA] relative">
      <div className="max-w-[1000px] mx-auto px-6 xl:px-[120px] py-20">
        {/* Section Header */}
        <div className="mb-30 text-center sticky top-20 z-0">
          <p className="font-onest text-lg font-medium text-black mb-3 tracking-wide uppercase opacity-70">
            Platform Capabilities
          </p>
          <h2 className="font-onest text-3xl md:text-5xl font-medium text-[#2A1638] tracking-tight leading-tight">
            Core <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#9F5AF0] to-[#7038BA]">Features</span>
          </h2>
        </div>

        {/* Features Stacking List */}
        <div className="flex flex-col gap-8 pb-32">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              className="sticky"
              style={{
                top: `${260 + idx * 40}px`, // Staggered sticky top position - Increased to avoid header overlap
                zIndex: idx + 1,
              }}
            >
              <div className="group relative flex flex-col md:flex-row gap-8 overflow-hidden rounded-[40px] p-8 md:p-12 bg-gradient-to-br from-white to-purple-50/30 backdrop-blur-md border border-purple-400/50 shadow-[0_8px_30px_rgb(0,0,0,0.04)] hover:shadow-[0_20px_40px_rgba(159,90,240,0.15)] hover:border-purple-200/80 transition-all duration-500 min-h-[300px]">
                
                {/* Watermark Number */}
                <span className="absolute -top-6 -right-6 text-[180px] font-bold text-black/[0.02] leading-none select-none pointer-events-none transition-colors duration-500 group-hover:text-purple-500/[0.03]">
                  {String(idx + 1).padStart(2, '0')}
                </span>

                {/* Icon & Title Section */}
                <div className="md:w-1/3 flex flex-col items-start relative z-10">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-100 to-purple-50 flex items-center justify-center mb-6 group-hover:scale-110 group-hover:rotate-3 transition-transform duration-500 shadow-lg shadow-purple-500/10 border border-white/50">
                    <feature.icon className="w-8 h-8 text-purple-600" />
                  </div>
                  <h3 className="font-onest text-2xl font-bold text-[#2A1638] mb-4 leading-tight group-hover:text-purple-900 transition-colors duration-300">{feature.title}</h3>
                  <div className="h-1 w-12 bg-purple-200 rounded-full group-hover:w-20 group-hover:bg-purple-400 transition-all duration-500" />
                </div>

                {/* Content Section */}
                <div className="md:w-2/3 flex flex-col relative z-10">
                   <p className="text-lg text-[#2A1638]/70 mb-8 leading-relaxed font-medium group-hover:text-[#2A1638]/90 transition-colors duration-300">{feature.goal}</p>
                   
                   <ul className="space-y-4 mt-auto">
                    {feature.capabilities.map((cap, i) => (
                      <li key={i} className="flex items-start gap-3 text-base text-[#2A1638]/80 group-hover:text-[#2A1638] transition-colors duration-300 delay-[50ms]">
                        <div className="mt-1 p-0.5 rounded-full bg-purple-100/80">
                          <CheckCircle className="w-4 h-4 text-purple-600 shrink-0" />
                        </div>
                        {cap}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default CoreFeatures;
