import { motion } from "framer-motion";
import { 
  Users, FileCheck, AlertTriangle, 
  Plug, Shield, CheckCircle, Workflow
} from "lucide-react";
import graph from "../../assets/graph-svgrepo-com.svg";
import collaborate from "../../assets/collaborate-svgrepo-com.svg";
import connect from "../../assets/data-integration-hub-svgrepo-com.svg";
import chart from "../../assets/chart-mixed-alt-svgrepo-com.svg";
import health from "../../assets/health-svgrepo-com.svg";
import openBook from "../../assets/open-book-svgrepo-com.svg";

const CoreFeatures = () => {
  const features = [
    {
      icon: Plug,
      title: "Living Knowledge Graph",
      goal: "Anseru connects directly to your real sources of truth: content, past RFPs, security documents, and public content.",
      capabilities: [
        "Each source is indexed with ownership, freshness, and expiry",
        "Improves accuracy with usage instead of decaying over time",
        "Shifts the problem from 'Did AI hallucinate?' to 'Which document needs updating?'",
      ]
    },
    {
      icon: Users,
      title: "Cross-Team Collaboration & Workflow",
      goal: "Collaborate seamlessly across sales, pre-sales, product, legal, and security teams.",
      capabilities: [
        "Real-time editing and commenting",
        "Role-based access and approvals",
        "Task tracking to assign ownership and reduce bottlenecks"
      ]
    },
    {
      icon: FileCheck,
      title: "Evidence & Citation Engine",
      goal: "Every answer generated by Anseru is backed by real evidence.",
      capabilities: [
        "Automatic source citations",
        "Secure document links instead of attachments",
        "Full traceability from answer to underlying document"

      ]
    },
    {
      icon: AlertTriangle,
      title: "Knowledge Health & Risk Monitoring",
      goal: "Expose risk before submission, not after.",
      capabilities: [
        "Monitors expiring certifications, outdated policies, and missing ownership",
        "Shifts the problem from 'Did AI hallucinate?' to 'Which document needs updating?'",
        "Shifts the problem from 'Did AI hallucinate?' to 'Which document needs updating?'",
      ]
    },
    {
      icon: Workflow,
      title: "Enterprise Integrations",
      goal: "Integrate effortlessly with your existing revenue and security stack.",
      capabilities: [
        "Connects with CRM systems, cloud storage providers, and communication tools",
        "Fits into existing workflows instead of forcing teams to change",
        "Fits into existing workflows instead of forcing teams to change"
      ]
    },
    {
      icon: Shield,
      title: "Governance, Analytics & Audit Readiness",
      goal: "Stay in control at every stage of the response lifecycle.",
      capabilities: [
        "Detailed activity logs with user actions and approval tracking",
        "Analytics on response quality, coverage gaps, and cycle times",
        "Audit-ready operations by default"
      ]
    }
  ];

  return (
    <section className="py-0 bg-[#FAFAFA] relative">
      <div className="max-w-[1400px] mx-auto px-6 xl:px-[120px]">
        {/* Section Header */}
        <div className="mb-12 lg:mb-20 text-center relative lg:sticky lg:top-25 z-0">
          <p className="font-onest text-lg font-medium text-black mb-3 tracking-wide uppercase opacity-70">
            Platform Capabilities
          </p>
          <h2 className="font-onest text-3xl md:text-5xl font-medium text-[#2A1638] tracking-tight leading-tight">
            Core <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#9F5AF0] to-[#7038BA]">Features</span>
          </h2>
        </div>

        {/* Features Stacking List */}
        <div className="flex flex-col gap-6 lg:gap-30 pb-20">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              className="relative lg:sticky"
              style={{
                // We apply the top offset logic but it only takes effect when position: sticky is active (lg screens)
                top: `${225 + idx * 10}px`, 
                zIndex: idx + 1,
              }}
            >
              <div className="group relative flex flex-col md:flex-row gap-8 overflow-hidden rounded-[40px] p-8 md:p-12 bg-gradient-to-br from-white to-purple-50/30 bg-white border border-purple-200/80 shadow-[0_0px_80px_-20px_rgba(202,168,232,0.5),0_0_0_1px_rgba(255,255,255,0.8)_inset] transition-all duration-500 h-[300px]">
                
                {/* Decorative Background SVG */}
                <FeatureBackground index={idx} />

                {/* Watermark Number */}
                <span className="absolute -top-6 -right-6 text-[180px] font-bold text-black/[0.02] leading-none select-none pointer-events-none transition-colors duration-500 text-purple-500/[0.03]">
                  {String(idx + 1).padStart(2, '0')}
                </span>

                {/* Icon & Title Section */}
                <div className="md:w-1/3 flex flex-col items-start relative z-10">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-100 to-purple-50 flex items-center justify-center mb-6 scale-110 rotate-3 transition-transform duration-500 shadow-lg shadow-purple-500/10 border border-white/50">
                    <feature.icon className="w-8 h-8 text-purple-600" />
                  </div>
                  <h3 className="font-onest text-2xl font-bold mb-4 leading-tight text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-indigo-900 transition-colors duration-300">
                    {feature.title}
                  </h3>
                  <div className="h-1 w-20 bg-purple-400 rounded-full transition-all duration-500" />
                </div>

                {/* Content Section */}
                <div className="md:w-2/3 flex flex-col relative z-10">
                   <p className="text-lg text-[#2A1638]/90 mb-8 leading-relaxed font-medium transition-colors duration-300">{feature.goal}</p>
                   
                   <ul className="space-y-4 mt-auto">
                    {feature.capabilities.map((cap, i) => (
                      <li key={i} className="flex items-start gap-3 text-base text-[#2A1638] transition-colors duration-300">
                        <div className="mt-1 p-0.5 rounded-full bg-purple-100/80">
                          <CheckCircle className="w-4 h-4 text-purple-600 shrink-0" />
                        </div>
                        {cap}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

const FeatureBackground = ({ index }: { index: number }) => {
  const commonProps = "absolute right-0 top-1/2 -translate-y-1/2 h-[120%] w-auto opacity-[0.05] text-white pointer-events-none p-10 select-none";
  
  switch (index) {
    case 0: // Living Knowledge Graph (Network/Nodes)
      return (
        <img src={graph} alt="" className={commonProps} />
      );
    case 1: // Collaboration (Connected Users)
      return (
        <img src={collaborate} alt="" className={commonProps} />
      );
    case 2: // Evidence (Document/Check)
      return (
        <img src={openBook} alt="" className={commonProps} loading="lazy" />
      );
    case 3: // Health/Risk (Pulse/Shield)
      return (
        <img src={health} alt="" className={commonProps} loading="lazy" />
      );
    case 4: // Integrations (Circuit/Connect)
      return (
        <img src={connect} alt="" className={commonProps} loading="lazy" />
      );
    case 5: // Analytics (Charts)
      return (
        <img src={chart} alt="" className={commonProps} loading="lazy" />
      );
    default:
      return null;
  }
};

export default CoreFeatures;
